import Head from 'next/head'
import { Inter } from '@next/font/google'
import Dashboard from '../../components/Dashboard'
import { useRouter } from 'next/router'
import { useSession } from 'next-auth/react'
import Loader from '../../components/Loader'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const router = useRouter()
  const {status, data: session} = useSession({
    required: true,
    onUnauthenticated(){
      router.push('/auth/signin')
    }
  })

  if(status === 'loading'){
    return <Loader />
  }

  console.log(session)

  return (
    <>
      <Head>
        <title>Spotify - Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Dashboard />
    </>
  )
}
